grpc:
  host: "0.0.0.0"
  port: "50052"
postgres:
  host: "auth-pg"
  port: "5432"
  user: "auth-user"
  password: "auth-password"
  dbname: "auth"
  sslmode: "disable"
jwt:
  refresh_token_expiration: 50m
  access_token_expiration: 5m
